stages:
  - test
  - build
  - deploy

test project:
  stage: test
  image: node:14.17.0
  script:
    - yarn install
    - yarn test

build project:
  stage: build
  image: node:14.17.0
  script:
    - yarn install
    - yarn build
  artifacts:
    paths:
      - /build

deploy to netlify:
  stage: deploy
  image: node:14.17.0
  script:
    - npm install -g netlify-cli
    - netlify deploy --dir=build --prod
